Repository codesquad-masters2025-team03/issue-tracker, pull requests merged in 2025-05, with the labels that each got.

#34 Be/johnnie
  be/build.gradle
  be/settings.gradle
  be/src/main/java/CodeSquad/IssueTracker/comment/Comment.java
  be/src/main/java/CodeSquad/IssueTracker/comment/CommentRepository.java
  be/src/main/java/CodeSquad/IssueTracker/comment/CommentUpdateDto.java
  be/src/main/java/CodeSquad/IssueTracker/comment/JdbcTemplatesCommentRepository.java
  be/src/main/java/CodeSquad/IssueTracker/home/HomeController.java
  be/src/main/java/CodeSquad/IssueTracker/home/HomeService.java
  be/src/main/java/CodeSquad/IssueTracker/home/dto/HomeResponseDto.java
  be/src/main/java/CodeSquad/IssueTracker/issue/Issue.java
  be/src/main/java/CodeSquad/IssueTracker/issue/IssueController.java
  be/src/main/java/CodeSquad/IssueTracker/issue/IssueRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issue/IssueService.java
  be/src/main/java/CodeSquad/IssueTracker/issue/JdbcTemplateIssueRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issue/dto/IssueCreateRequest.java
  be/src/main/java/CodeSquad/IssueTracker/issue/dto/IssueUpdateDto.java
  be/src/main/java/CodeSquad/IssueTracker/issueAssignee/IssueAssignee.java
  be/src/main/java/CodeSquad/IssueTracker/issueAssignee/IssueAssigneeRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issueAssignee/IssueAssigneeService.java
  be/src/main/java/CodeSquad/IssueTracker/issueAssignee/JdbcTemplateAssigneeRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issueLabel/IssueLabel.java
  be/src/main/java/CodeSquad/IssueTracker/issueLabel/IssueLabelRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issueLabel/IssueLabelService.java
  be/src/main/java/CodeSquad/IssueTracker/issueLabel/JdbcTemplateIssueLabelRepository.java
  be/src/main/java/CodeSquad/IssueTracker/label/JdbcTemplatesLabelRepository.java
  be/src/main/java/CodeSquad/IssueTracker/label/Label.java
  be/src/main/java/CodeSquad/IssueTracker/label/LabelRepository.java
  be/src/main/java/CodeSquad/IssueTracker/label/LabelService.java
  be/src/main/java/CodeSquad/IssueTracker/label/LabelUpdateDto.java
  be/src/main/java/CodeSquad/IssueTracker/milestone/JdbcTemplatesMilestoneRepository.java
  be/src/main/java/CodeSquad/IssueTracker/milestone/Milestone.java
  be/src/main/java/CodeSquad/IssueTracker/milestone/MilestoneRepository.java
  be/src/main/java/CodeSquad/IssueTracker/milestone/MilestoneService.java
  be/src/main/java/CodeSquad/IssueTracker/milestone/MilestoneUpdateDto.java
  be/src/main/java/CodeSquad/IssueTracker/user/JdbcTemplatesUserRepository.java
  be/src/main/java/CodeSquad/IssueTracker/user/User.java
  be/src/main/java/CodeSquad/IssueTracker/user/UserRepository.java
  be/src/main/java/CodeSquad/IssueTracker/user/UserService.java
  be/src/main/resources/application.properties
  be/src/main/resources/application.yml
  be/src/test/java/CodeSquad/IssueTracker/IssueTrackerApplicationTests.java
  be/src/test/java/CodeSquad/IssueTracker/issue/IssueServiceTest.java
  be/src/test/java/CodeSquad/IssueTracker/label/LabelServiceTest.java
  be/src/test/java/CodeSquad/IssueTracker/milestone/MilestoneServiceTest.java
  be/src/test/java/CodeSquad/IssueTracker/user/UserServiceTest.java
  be/src/test/resources/application-test.yml
  be/src/test/resources/schema.sql
Labels: feature

#35 [BE/MUD] JWT 토근 기반 로그인 기능 구현
  be/build.gradle
  be/src/main/java/CodeSquad/IssueTracker/global/GlobalExceptionHandler.java
  be/src/main/java/CodeSquad/IssueTracker/global/dto/BaseResponseDto.java
  be/src/main/java/CodeSquad/IssueTracker/global/exception/CustomException.java
  be/src/main/java/CodeSquad/IssueTracker/jwt/exception/JwtValidationException.java
  be/src/main/java/CodeSquad/IssueTracker/jwt/filter/FilterConfig.java
  be/src/main/java/CodeSquad/IssueTracker/jwt/filter/JwtAuthFilter.java
  be/src/main/java/CodeSquad/IssueTracker/jwt/util/JWTUtil.java
  be/src/main/java/CodeSquad/IssueTracker/login/controller/LoginController.java
  be/src/main/java/CodeSquad/IssueTracker/login/dto/LoginRequestDto.java
  be/src/main/java/CodeSquad/IssueTracker/login/dto/LoginResponseDto.java
  be/src/main/java/CodeSquad/IssueTracker/login/exception/PasswordMismatchException.java
  be/src/main/java/CodeSquad/IssueTracker/login/exception/UserNotFoundException.java
  be/src/main/java/CodeSquad/IssueTracker/login/service/LoginService.java
  be/src/main/java/CodeSquad/IssueTracker/user/JdbcTemplatesUserRepository.java
  be/src/main/java/CodeSquad/IssueTracker/user/User.java
  be/src/main/resources/application.yml
  be/src/test/java/CodeSquad/IssueTracker/login/LoginServiceTest.java
Labels: feature, BE

#49 2주차 코드리뷰를 위한 브밴치 merge
  be/build.gradle
  be/src/main/java/CodeSquad/IssueTracker/global/GlobalExceptionHandler.java
  be/src/main/java/CodeSquad/IssueTracker/global/dto/BaseResponseDto.java
  be/src/main/java/CodeSquad/IssueTracker/global/exception/CustomException.java
  be/src/main/java/CodeSquad/IssueTracker/jwt/exception/JwtValidationException.java
  be/src/main/java/CodeSquad/IssueTracker/jwt/filter/FilterConfig.java
  be/src/main/java/CodeSquad/IssueTracker/jwt/filter/JwtAuthFilter.java
  be/src/main/java/CodeSquad/IssueTracker/jwt/util/JWTUtil.java
  be/src/main/java/CodeSquad/IssueTracker/login/controller/LoginController.java
  be/src/main/java/CodeSquad/IssueTracker/login/dto/LoginRequestDto.java
  be/src/main/java/CodeSquad/IssueTracker/login/dto/LoginResponseDto.java
  be/src/main/java/CodeSquad/IssueTracker/login/exception/PasswordMismatchException.java
  be/src/main/java/CodeSquad/IssueTracker/login/exception/UserNotFoundException.java
  be/src/main/java/CodeSquad/IssueTracker/login/service/LoginService.java
  be/src/main/java/CodeSquad/IssueTracker/user/JdbcTemplatesUserRepository.java
  be/src/main/java/CodeSquad/IssueTracker/user/User.java
  be/src/main/resources/application.yml
  be/src/test/java/CodeSquad/IssueTracker/login/LoginServiceTest.java
Labels: feature, BE

#53 [BE - Johnnie] 이슈트레커 ERD 확립 및 서로 객체들간의 필요한 데이터 핸들 로직 작성
  be/src/main/java/CodeSquad/IssueTracker/comment/Comment.java
  be/src/main/java/CodeSquad/IssueTracker/comment/CommentController.java
  be/src/main/java/CodeSquad/IssueTracker/comment/CommentService.java
  be/src/main/java/CodeSquad/IssueTracker/comment/JdbcTemplatesCommentRepository.java
  be/src/main/java/CodeSquad/IssueTracker/comment/commnetimage/CommentImage.java
  be/src/main/java/CodeSquad/IssueTracker/comment/commnetimage/CommentImageRepository.java
  be/src/main/java/CodeSquad/IssueTracker/comment/commnetimage/CommentImageService.java
  be/src/main/java/CodeSquad/IssueTracker/comment/commnetimage/JdbcTemplateCommentImageRepository.java
  be/src/main/java/CodeSquad/IssueTracker/comment/dto/CommentRequestDto.java
  be/src/main/java/CodeSquad/IssueTracker/comment/dto/CommentResponse.java
  be/src/main/java/CodeSquad/IssueTracker/comment/dto/CommentResponseDto.java
  be/src/main/java/CodeSquad/IssueTracker/global/GlobalExceptionHandler.java
  be/src/main/java/CodeSquad/IssueTracker/global/dto/BaseResponseDto.java
  be/src/main/java/CodeSquad/IssueTracker/global/exception/NoAuthorityException.java
  be/src/main/java/CodeSquad/IssueTracker/global/exception/NoParametersException.java
  be/src/main/java/CodeSquad/IssueTracker/global/exception/UserNotFoundException.java
  be/src/main/java/CodeSquad/IssueTracker/global/exception/message/Error.java
  be/src/main/java/CodeSquad/IssueTracker/global/exception/model/CustomException.java
  be/src/main/java/CodeSquad/IssueTracker/issue/Issue.java
  be/src/main/java/CodeSquad/IssueTracker/issue/IssueController.java
  be/src/main/java/CodeSquad/IssueTracker/issue/IssueService.java
  be/src/main/java/CodeSquad/IssueTracker/issue/dto/IssueCreateRequest.java
  be/src/main/java/CodeSquad/IssueTracker/issue/issueimage/IssueImage.java
  be/src/main/java/CodeSquad/IssueTracker/issue/issueimage/IssueImageRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issue/issueimage/IssueImageService.java
  be/src/main/java/CodeSquad/IssueTracker/issue/issueimage/JdbcTemplateIssueImageRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issueAssignee/IssueAssignee.java
  be/src/main/java/CodeSquad/IssueTracker/issueAssignee/IssueAssigneeRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issueAssignee/IssueAssigneeService.java
  be/src/main/java/CodeSquad/IssueTracker/issueAssignee/JdbcTemplateAssigneeRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issueAssignee/dto/IssueAssigneeResponse.java
  be/src/main/java/CodeSquad/IssueTracker/issueLabel/IssueLabel.java
  be/src/main/java/CodeSquad/IssueTracker/issueLabel/IssueLabelRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issueLabel/IssueLabelService.java
  be/src/main/java/CodeSquad/IssueTracker/issueLabel/JdbcTemplateIssueLabelRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issueLabel/dto/IssueLabelResponse.java
  be/src/main/java/CodeSquad/IssueTracker/login/exception/PasswordMismatchException.java
  be/src/main/java/CodeSquad/IssueTracker/login/exception/UserNotFoundException.java
  be/src/main/java/CodeSquad/IssueTracker/milestone/JdbcTemplatesMilestoneRepository.java
  be/src/main/java/CodeSquad/IssueTracker/milestone/Milestone.java
  be/src/main/java/CodeSquad/IssueTracker/milestone/MilestoneRepository.java
  be/src/main/java/CodeSquad/IssueTracker/milestone/MilestoneService.java
  be/src/main/java/CodeSquad/IssueTracker/user/User.java
  be/src/main/java/CodeSquad/IssueTracker/util/S3Uploader.java
  be/src/main/resources/errors.properties
  be/src/test/java/CodeSquad/IssueTracker/issue/IssueServiceTest.java
Labels: BE

#65 [Milo,FE] - ✨ 필터 드롭다운 기능 및 이슈 상태 제어 기능 통합 구현
  fe/mock-server/index.js
  fe/mock-server/mainPage.json
  fe/mock-server/reponse2.json
  fe/package.json
  fe/src/api/toggleStatus.js
  fe/src/base-ui/issueListPage/IssueListHeader/SelectDisplayer.jsx
  fe/src/base-ui/utils/CheckBox.jsx
  fe/src/pages/IssueListPage/index.jsx
  fe/src/stores/filterStore.js
  fe/src/stores/labelStore.js
  fe/src/stores/useCheckBoxStore.js
  fe/src/units/KanbanMain/IssueItem/ItemLabels.jsx
  fe/src/units/KanbanMain/IssueItem/index.jsx
  fe/src/units/deepEqualFast/deepEqualFast.js
  fe/src/units/deepEqualFast/deepEqualFast.test.js
  fe/src/units/detailFilterModal/DetailFilterTriggerButton.jsx
  fe/src/units/kanbanHeader/IsOpenFilter.jsx
  fe/src/units/kanbanHeader/StatusEditDropDown.jsx
  fe/src/units/kanbanHeader/TotalCheckBox.jsx
  fe/src/units/mainPageHeaderTap/FilterBar.jsx
  fe/src/utils/dropDown/DropdownMenuTemplate.jsx
  fe/src/utils/dropDown/DropdownMenuTemplate.styles.js
Labels: unit, feature, FE

#75 [FE,Milo] - 1차 배포용 프론트엔드 최종 구현 완료
  fe/mock-server/index.js
  fe/mock-server/mainPage.json
  fe/src/api/index.js
  fe/src/api/issues.js
  fe/src/api/toggleStatus.js
  fe/src/base-ui/IssuePage/NewIssueTile.jsx
  fe/src/base-ui/IssuePage/TitleForm.jsx
  fe/src/base-ui/detailFilterModal/ScrollFilterList.jsx
  fe/src/base-ui/utils/IssueStatusSidebar/AddStatusButton.jsx
  fe/src/base-ui/utils/IssueStatusSidebar/AddStatusToggle.jsx
  fe/src/base-ui/utils/IssueStatusSidebar/getToggleButton.js
  fe/src/pages/IssueListPage/index.jsx
  fe/src/stores/IssueDetailStore.js
  fe/src/units/kanbanHeader/StatusEditDropDown.jsx
  fe/src/units/mainPageHeaderTap/FilterBar.jsx
  fe/src/utils/mapToUnifiedId/mapToUnifiedId.js
  fe/src/utils/mapToUnifiedId/mapToUnifiedId.test.js
Labels: page, FE

#84 [FE,Milo] - FE 배포 위한 dev 머지 요청
  fe/mock-server/index.js
  fe/src/api/index.js
  fe/src/base-ui/IssuePage/MilestoneProgressBar.jsx
  fe/src/base-ui/utils/IssueStatusSidebar/AddStatusToggle.jsx
  fe/src/base-ui/utils/IssueStatusSidebar/GetToggleButton.jsx
  fe/src/base-ui/utils/IssueStatusSidebar/SelectedElements.jsx
  fe/src/base-ui/utils/IssueStatusSidebar/storeMannager.js
  fe/src/pages/IssueListPage/index.jsx
  fe/src/pages/NewIssuePage/index.jsx
  fe/src/stores/IssueDetailStore.js
  fe/src/stores/issuesStore.js
  fe/src/units/KanbanMain/IssueItem/ItemLabels.jsx
  fe/src/units/SideBar/index.jsx
  fe/src/utils/common/someHandler.js
  fe/src/utils/common/someHandler.test.js
  fe/src/utils/mapToUnifiedId/mapIssueListToUnifiedId.js
  fe/src/utils/mapToUnifiedId/mapIssueListToUnifiedId.test.js
Labels: FE

#89 [BE/MUD] 3주차 리뷰를 위한 merge
  be/src/main/java/CodeSquad/IssueTracker/home/HomeController.java
  be/src/main/java/CodeSquad/IssueTracker/home/HomeService.java
  be/src/main/java/CodeSquad/IssueTracker/home/dto/HomeResponseDto.java
  be/src/main/java/CodeSquad/IssueTracker/home/dto/IssueFilterRequestDto.java
  be/src/main/java/CodeSquad/IssueTracker/issue/IssueRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issue/IssueService.java
  be/src/main/java/CodeSquad/IssueTracker/issue/JdbcTemplateIssueRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issue/dto/FilteredIssueDto.java
  be/src/main/java/CodeSquad/IssueTracker/issueAssignee/IssueAssigneeRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issueAssignee/JdbcTemplateAssigneeRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issueLabel/IssueLabelRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issueLabel/JdbcTemplateIssueLabelRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issueLabel/dto/SummaryLabelDto.java
  be/src/main/java/CodeSquad/IssueTracker/jwt/util/JWTUtil.java
  be/src/main/java/CodeSquad/IssueTracker/milestone/dto/SummaryMilestoneDto.java
  be/src/main/java/CodeSquad/IssueTracker/user/JdbcTemplatesUserRepository.java
  be/src/main/java/CodeSquad/IssueTracker/user/UserRepository.java
  be/src/main/java/CodeSquad/IssueTracker/user/UserService.java
  be/src/main/java/CodeSquad/IssueTracker/user/dto/DetailUserDto.java
  be/src/main/java/CodeSquad/IssueTracker/user/dto/SummaryUserDto.java
Labels: feature, BE

#88 [BE/MUD] 이슈 필터링 기능 구현
  be/src/main/java/CodeSquad/IssueTracker/home/HomeController.java
  be/src/main/java/CodeSquad/IssueTracker/home/HomeService.java
  be/src/main/java/CodeSquad/IssueTracker/home/dto/HomeResponseDto.java
  be/src/main/java/CodeSquad/IssueTracker/home/dto/IssueFilterRequestDto.java
  be/src/main/java/CodeSquad/IssueTracker/issue/IssueRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issue/IssueService.java
  be/src/main/java/CodeSquad/IssueTracker/issue/JdbcTemplateIssueRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issue/dto/FilteredIssueDto.java
  be/src/main/java/CodeSquad/IssueTracker/issueAssignee/IssueAssigneeRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issueAssignee/JdbcTemplateAssigneeRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issueLabel/IssueLabelRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issueLabel/JdbcTemplateIssueLabelRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issueLabel/dto/SummaryLabelDto.java
  be/src/main/java/CodeSquad/IssueTracker/jwt/util/JWTUtil.java
  be/src/main/java/CodeSquad/IssueTracker/milestone/dto/SummaryMilestoneDto.java
  be/src/main/java/CodeSquad/IssueTracker/user/JdbcTemplatesUserRepository.java
  be/src/main/java/CodeSquad/IssueTracker/user/UserRepository.java
  be/src/main/java/CodeSquad/IssueTracker/user/UserService.java
  be/src/main/java/CodeSquad/IssueTracker/user/dto/DetailUserDto.java
  be/src/main/java/CodeSquad/IssueTracker/user/dto/SummaryUserDto.java
Labels: feature, BE

#93 [BE/MUD] - 댓글 남긴 이슈 필터링 기능 구현
  be/src/main/java/CodeSquad/IssueTracker/issue/JdbcTemplateIssueRepository.java
Labels: feature, BE

#98 [BE/MUD] - 이슈 페이네이션 기능 merge 요청
  be/src/main/java/CodeSquad/IssueTracker/home/HomeController.java
  be/src/main/java/CodeSquad/IssueTracker/home/HomeService.java
  be/src/main/java/CodeSquad/IssueTracker/home/dto/HomeResponseDto.java
  be/src/main/java/CodeSquad/IssueTracker/home/dto/IssueFilterCondition.java
  be/src/main/java/CodeSquad/IssueTracker/home/dto/MetaData.java
  be/src/main/java/CodeSquad/IssueTracker/issue/IssueFilterQueryBuilder.java
  be/src/main/java/CodeSquad/IssueTracker/issue/IssueRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issue/IssueService.java
  be/src/main/java/CodeSquad/IssueTracker/issue/JdbcTemplateIssueRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issueAssignee/IssueAssigneeService.java
Labels: feature, BE

#109 [BE/MUD] JWT 토큰에 사용자 ID 누락으로 발생한 이슈 필터링 오류 수정
  be/src/main/java/CodeSquad/IssueTracker/jwt/filter/JwtAuthFilter.java
  be/src/main/java/CodeSquad/IssueTracker/jwt/util/JWTUtil.java
Labels: bug, BE

#114 [BE/MUD] - 이슈 상세 조회 API 응답 불일치한 필드명 수정 및 누락된 데이터 추가
  be/src/main/java/CodeSquad/IssueTracker/comment/dto/CommentResponseDto.java
  be/src/main/java/CodeSquad/IssueTracker/global/message/SuccessMessage.java
  be/src/main/java/CodeSquad/IssueTracker/issue/IssueController.java
  be/src/main/java/CodeSquad/IssueTracker/issue/IssueService.java
  be/src/main/java/CodeSquad/IssueTracker/issue/dto/IssueDetailResponse.java
  be/src/main/java/CodeSquad/IssueTracker/issue/dto/IssueWithAuthorInfo.java
  be/src/main/java/CodeSquad/IssueTracker/issueLabel/JdbcTemplateIssueLabelRepository.java
  be/src/main/java/CodeSquad/IssueTracker/issueLabel/dto/IssueLabelResponse.java
Labels: bug, BE
